#############################
# Docker Quickstart
# DC_ENV: dev
#############################

version: "3.4"

services:
  app:
    build:
      context: ${DOCKER_CONTEXT:-./docker}/bulletinboard
      args:
        - NODE_VERSION=${NODE_VERSION:-13-alpine3.11}
    ports: 
      - 8080:8080